apiVersion: v1
kind: Service
metadata:
  name:  ms-frontend-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
  - name: ms-frontend
    port: 80
    targetPort: 3000
    nodePort: 30123
  selector:
    app: ms-frontend


    

